--h2
/gpfs/commons/home/clakhani/data/summary_stats/alzheimers/AD_Kunkle_etal_Stage1.parquet
--ref-ld-chr
$bl/baselineLD.,$rm/roadmap_merged_DNase.chr,$rm/roadmap_merged_H3K27ac.chr,$rm/roadmap_merged_H3K4me1.chr,$rm/roadmap_merged_H3K4me3.chr,$exp/expecto_TF_,$exp/expecto_DNASE_,$exp/expecto_H3K27ac_,$exp/expecto_H3K4me1_,$exp/expecto_H3K4me3_,$bat/brain_atac_seq_chr
--w-ld-chr
/gpfs/commons/home/clakhani/data/ldsc_data/weights_hm3_no_hla/weights.
--overlap-annot
--out
/gpfs/commons/home/clakhani/data/summary_stats/alzheimers/test
--overlap-annot
--not-M-5-50
--print-coefficients
--loco
--enet